const cloud = require('wx-server-sdk');
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
const db = cloud.database();
const _ = db.command;

function openId() { const c = cloud.getWXContext(); return c.OPENID || c.FROM_OPENID || ''; }
function fail(error) { return { success: false, error }; }
async function teacherDoc(id) { const r = await db.collection('users').where({ _id: id }).limit(1).get(); return (r.data || [])[0] || null; }
async function requireTeacher() { const id = openId(); if (!id) throw new Error('NOT_TEACHER'); const user = await teacherDoc(id); if (!user || user.role !== 'teacher') throw new Error('NOT_TEACHER'); return id; }
function normalizeClass(c) { return { id: c._id, name: c.name, grade: c.grade || '', joinCode: c.joinCode, studentCount: c.studentCount || 0, createdAt: c.createdAt }; }

exports.main = async event => {
  try {
    if (event.action === 'joinClass') return joinClass(event);
    if (event.action === 'myClasses') return myClasses();
    if (event.action === 'myMessages') return myMessages();
    if (event.action === 'myNotebooks') return myNotebooks();
    if (event.action === 'myAssignments') return myAssignments();
    if (event.action === 'myAssignmentDetail') return myAssignmentDetail(event);
    if (event.action === 'submitAssignment') return submitAssignment(event);
    const teacherId = await requireTeacher();
    switch (event.action) {
      case 'dashboard': return dashboard(teacherId);
      case 'createClass': return createClass(teacherId, event);
      case 'students': return students(teacherId, event.classId);
      case 'studentQuestions': return studentQuestions(teacherId, event);
      case 'teacherQuestions': return teacherQuestions(teacherId);
      case 'publishNotebook': return publishNotebook(teacherId, event);
      case 'createAssignment': return createAssignment(teacherId, event);
      case 'assignmentSubmissions': return assignmentSubmissions(teacherId, event);
      case 'teacherAssignments': return teacherAssignments(teacherId);
      case 'gradeAssignment': return gradeAssignment(teacherId, event);
      case 'parentReport': return parentReport(teacherId, event);
      case 'message': return message(teacherId, event);
      default: return fail(`Unknown action: ${event.action}`);
    }
  } catch (e) { if (e.message === 'NOT_TEACHER') return fail('NOT_TEACHER'); console.error(e); return fail(e.message || '教师工作台加载失败'); }
};

async function ownedClasses(teacherId) { const r = await db.collection('classes').where({ teacherId, isDeleted: false }).orderBy('createdAt','desc').get(); return r.data || []; }
async function students(teacherId, classId) { if (!classId) return fail('Missing classId'); const cls = (await db.collection('classes').doc(classId).get()).data; if (!cls || cls.teacherId !== teacherId) return fail('无权访问该班级'); const r = await db.collection('class_members').where({ classId, isDeleted: false }).get(); const members = r.data || []; if (!members.length) return { success:true,data:[] }; const ids = members.map(m => m.studentId); const users = await db.collection('users').where({ _id: _.in(ids) }).get(); const questions = await Promise.all(ids.map(id => db.collection('questions').where({ ownerId:id, isDeleted:false }).count().then(x=>x.total).catch(()=>0))); return { success:true,data:(users.data||[]).map((u,i)=>({ id:u._id,nickName:u.nickName||'',avatarFileID:u.avatarFileID||'',questionCount:questions[i]||0,practiceCount:0,lastActiveAt:u.updatedAt||'' })) }; }
async function dashboard(teacherId) { const raw = await ownedClasses(teacherId); const classes = await Promise.all(raw.map(async c => ({ ...normalizeClass(c), studentCount:(await db.collection('class_members').where({ classId:c._id,isDeleted:false }).count()).total }))); const selected = classes[0]; const list = selected ? await students(teacherId, selected.id) : { data:[] }; const msg = await db.collection('teacher_messages').where({ teacherId, isDeleted:false, readAt:'' }).count().catch(()=>({total:0})); return { success:true,data:{ classes, students:list.data||[], studentCount:classes.reduce((n,c)=>n+c.studentCount,0), messageCount:msg.total||0 } }; }
async function createClass(teacherId,event) { const name=String(event.name||'').trim(); if(!name) return fail('请输入班级名称'); const code=Math.random().toString(36).slice(2,8).toUpperCase(); const now=new Date().toISOString(); const r=await db.collection('classes').add({data:{teacherId,name,joinCode:code,isDeleted:false,createdAt:now,updatedAt:now}}); return {success:true,data:{id:r._id,name,joinCode:code,studentCount:0}}; }
async function message(teacherId,event) { const content=String(event.content||'').trim(); if(!event.classId||!content) return fail('留言内容不能为空'); const cls=(await db.collection('classes').doc(event.classId).get()).data; if(!cls||cls.teacherId!==teacherId)return fail('无权操作该班级'); const now=new Date().toISOString(); const r=await db.collection('teacher_messages').add({data:{teacherId,classId:event.classId,content,isDeleted:false,createdAt:now,updatedAt:now,readAt:''}}); return {success:true,data:{id:r._id,content,createdAt:now}}; }
async function joinClass(event) { const studentId=openId(); const joinCode=String(event.joinCode||'').trim().toUpperCase(); if(!studentId||!joinCode)return fail('请输入班级加入码'); const r=await db.collection('classes').where({joinCode,isDeleted:false}).limit(1).get(); const cls=(r.data||[])[0]; if(!cls)return fail('加入码无效'); const existing=await db.collection('class_members').where({classId:cls._id,studentId,isDeleted:false}).count(); if(existing.total>0)return {success:true,data:{classId:cls._id,name:cls.name,alreadyJoined:true}}; const now=new Date().toISOString(); await db.collection('class_members').add({data:{classId:cls._id,studentId,isDeleted:false,createdAt:now,updatedAt:now}}); return {success:true,data:{classId:cls._id,name:cls.name,alreadyJoined:false}}; }
async function myClasses() { const studentId=openId(); if(!studentId)return fail('未获取到用户身份'); const memberships=await db.collection('class_members').where({studentId,isDeleted:false}).get(); const classes=await Promise.all((memberships.data||[]).map(async m=>{const r=await db.collection('classes').doc(m.classId).get(); const c=r.data; if(!c||c.isDeleted)return null; const t=await teacherDoc(c.teacherId); return {id:c._id,name:c.name,grade:c.grade||'',teacherName:(t&&t.nickName)||'教师',joinedAt:m.createdAt||''};})); return {success:true,data:classes.filter(Boolean)}; }
async function myMessages() { const studentId=openId(); if(!studentId)return fail('未获取到用户身份'); const memberships=await db.collection('class_members').where({studentId,isDeleted:false}).get(); const ids=(memberships.data||[]).map(m=>m.classId); if(!ids.length)return {success:true,data:[]}; const r=await db.collection('teacher_messages').where({classId:_.in(ids),isDeleted:false}).orderBy('createdAt','desc').limit(50).get(); return {success:true,data:r.data||[]}; }
async function myNotebooks() { const studentId=openId(); if(!studentId)return fail('未获取到用户身份'); const memberships=await db.collection('class_members').where({studentId,isDeleted:false}).get(); const ids=(memberships.data||[]).map(m=>m.classId); if(!ids.length)return {success:true,data:[]}; const r=await db.collection('class_notebooks').where({classId:_.in(ids),isDeleted:false}).orderBy('createdAt','desc').limit(30).get(); const notebooks=await Promise.all((r.data||[]).map(async n=>{const qs=await db.collection('questions').where({_id:_.in(n.questionIds||[]),isDeleted:false}).get().catch(()=>({data:[]})); const cls=await db.collection('classes').doc(n.classId).get().catch(()=>({data:null})); return {id:n._id,title:n.title,questionCount:(n.questionIds||[]).length,className:cls.data&&cls.data.name||'班级',questions:(qs.data||[]).map(q=>({id:q._id,content:q.content||''}))};})); return {success:true,data:notebooks}; }
async function studentQuestions(teacherId,event) { const studentId=String(event.studentId||''); const classId=String(event.classId||''); if(!studentId||!classId)return fail('参数不完整'); const cls=(await db.collection('classes').doc(classId).get()).data; if(!cls||cls.teacherId!==teacherId)return fail('无权访问该班级'); const member=(await db.collection('class_members').where({classId,studentId,isDeleted:false}).count()).total; if(!member)return fail('学生不在该班级'); const r=await db.collection('questions').where({ownerId:studentId,isDeleted:false}).orderBy('createdAt','desc').limit(50).get(); return {success:true,data:(r.data||[]).map(q=>({id:q._id,content:q.content||'',category:q.category||'',difficulty:q.difficulty||'MEDIUM',aiStatus:q.aiStatus||'',createdAt:q.createdAt||''}))}; }
async function teacherQuestions(teacherId) { const classes=await ownedClasses(teacherId); const classIds=classes.map(c=>c._id); if(!classIds.length)return {success:true,data:[]}; const members=await db.collection('class_members').where({classId:_.in(classIds),isDeleted:false}).get(); const studentIds=Array.from(new Set((members.data||[]).map(m=>m.studentId).filter(Boolean))); if(!studentIds.length)return {success:true,data:[]}; const r=await db.collection('questions').where({ownerId:_.in(studentIds),isDeleted:false}).orderBy('createdAt','desc').limit(100).get(); return {success:true,data:(r.data||[]).map(q=>({id:q._id,content:q.content||'',category:q.category||'',difficulty:q.difficulty||'MEDIUM',ownerId:q.ownerId||''}))}; }
async function publishNotebook(teacherId,event) { const classId=String(event.classId||''); const title=String(event.title||'班级错题练习').trim(); const ids=Array.isArray(event.questionIds)?event.questionIds.filter(Boolean):[]; if(!classId||!ids.length)return fail('请选择班级和题目'); const cls=(await db.collection('classes').doc(classId).get()).data; if(!cls||cls.teacherId!==teacherId)return fail('无权操作该班级'); const now=new Date().toISOString(); const r=await db.collection('class_notebooks').add({data:{teacherId,classId,title,questionIds:ids,isDeleted:false,createdAt:now,updatedAt:now}}); return {success:true,data:{id:r._id,title,questionCount:ids.length,createdAt:now}}; }
async function createAssignment(teacherId,event) { const classId=String(event.classId||''); const title=String(event.title||'班级作业').trim(); const ids=Array.isArray(event.questionIds)?event.questionIds.filter(Boolean):[]; if(!classId||!ids.length)return fail('请选择班级和题目'); const cls=(await db.collection('classes').doc(classId).get()).data; if(!cls||cls.teacherId!==teacherId)return fail('无权操作该班级'); const now=new Date().toISOString(); const r=await db.collection('assignments').add({data:{teacherId,classId,title,questionIds:ids,dueAt:event.dueAt||'',isDeleted:false,createdAt:now,updatedAt:now}}); return {success:true,data:{id:r._id,title,questionCount:ids.length,createdAt:now}}; }
async function assignmentSubmissions(teacherId,event) { const a=(await db.collection('assignments').doc(String(event.assignmentId||'')).get()).data; if(!a||a.teacherId!==teacherId)return fail('无权访问该作业'); const r=await db.collection('assignment_submissions').where({assignmentId:a._id}).get(); return {success:true,data:r.data||[]}; }
async function teacherAssignments(teacherId) { const r=await db.collection('assignments').where({teacherId,isDeleted:false}).orderBy('createdAt','desc').limit(50).get(); return {success:true,data:r.data||[]}; }
async function gradeAssignment(teacherId,event) { const id=String(event.submissionId||''); const score=Number(event.score); if(!id||Number.isNaN(score)||score<0)return fail('请输入有效分数'); const r=await db.collection('assignment_submissions').doc(id).get(); const sub=r.data; if(!sub)return fail('提交记录不存在'); const a=(await db.collection('assignments').doc(sub.assignmentId).get()).data; if(!a||a.teacherId!==teacherId)return fail('无权批改该作业'); await db.collection('assignment_submissions').doc(id).update({data:{score,status:'graded',gradedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}); return {success:true,data:{id,score,status:'graded'}}; }
async function parentReport(teacherId,event) { const classId=String(event.classId||''); const cls=(await db.collection('classes').doc(classId).get()).data; if(!cls||cls.teacherId!==teacherId)return fail('无权访问该班级'); const members=(await db.collection('class_members').where({classId,isDeleted:false}).get()).data||[]; const ids=members.map(m=>m.studentId); const users=ids.length?(await db.collection('users').where({_id:_.in(ids)}).get()).data||[]:[]; const assignments=(await db.collection('assignments').where({classId,isDeleted:false}).get()).data||[]; const submissions=ids.length?(await db.collection('assignment_submissions').where({studentId:_.in(ids)}).get()).data||[]:[]; const rows=await Promise.all(ids.map(async id=>({studentId:id,nickName:((users.find(u=>u._id===id)||{}).nickName)||'未设置昵称',questionCount:(await db.collection('questions').where({ownerId:id,isDeleted:false}).count()).total,submitted:submissions.filter(s=>s.studentId===id).length,graded:submissions.filter(s=>s.studentId===id&&s.status==='graded').length,averageScore:(()=>{const a=submissions.filter(s=>s.studentId===id&&typeof s.score==='number');return a.length?Math.round(a.reduce((n,s)=>n+s.score,0)/a.length):null})()}))); const now=new Date().toISOString(); const report={teacherId,classId,className:cls.name,title:`${cls.name} 学习情况报告`,createdAt:now,students:rows,assignmentCount:assignments.length}; const saved=await db.collection('parent_reports').add({data:report}); return {success:true,data:{id:saved._id,...report}}; }
async function myAssignments() { const studentId=openId(); if(!studentId)return fail('未获取到用户身份'); const ms=await db.collection('class_members').where({studentId,isDeleted:false}).get(); const ids=(ms.data||[]).map(m=>m.classId); if(!ids.length)return {success:true,data:[]}; const r=await db.collection('assignments').where({classId:_.in(ids),isDeleted:false}).orderBy('createdAt','desc').limit(30).get(); return {success:true,data:r.data||[]}; }
async function myAssignmentDetail(event) { const studentId=openId(); const id=String(event.assignmentId||''); const a=(await db.collection('assignments').doc(id).get()).data; if(!a||a.isDeleted)return fail('作业不存在'); const member=await db.collection('class_members').where({classId:a.classId,studentId,isDeleted:false}).count(); if(!member.total)return fail('不在该班级'); const q=await db.collection('questions').where({_id:_.in(a.questionIds||[]),isDeleted:false}).get(); return {success:true,data:{...a,questions:q.data||[]}}; }
async function submitAssignment(event) { const studentId=openId(); const id=String(event.assignmentId||''); if(!studentId||!id)return fail('参数不完整'); const a=(await db.collection('assignments').doc(id).get()).data; if(!a||a.isDeleted)return fail('作业不存在'); const member=(await db.collection('class_members').where({classId:a.classId,studentId,isDeleted:false}).count()).total; if(!member)return fail('不在该班级'); const now=new Date().toISOString(); const old=await db.collection('assignment_submissions').where({assignmentId:id,studentId}).limit(1).get(); const data={assignmentId:id,studentId,answers:event.answers||[],status:'submitted',score:null,submittedAt:now,updatedAt:now}; if((old.data||[])[0]) await db.collection('assignment_submissions').doc(old.data[0]._id).update({data}); else await db.collection('assignment_submissions').add({data}); return {success:true,data:{status:'submitted',submittedAt:now}}; }
